# Generated by Django 6.1.1 on 2026-09-14 19:53

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='usuario', max_length=150, unique=True, verbose_name='usuario')),
                ('password', models.CharField(db_column='senha', max_length=128, verbose_name='senha')),
                ('first_name', models.CharField(blank=True, db_column='primeiro_nome', max_length=150, verbose_name='primeiro nome')),
                ('last_name', models.CharField(blank=True, db_column='sobrenome', max_length=150, verbose_name='sobrenome')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, verbose_name='email')),
                ('is_staff', models.BooleanField(db_column='membro_equipe', default=False, verbose_name='membro da equipe')),
                ('is_active', models.BooleanField(db_column='ativo', default=True, verbose_name='ativo')),
                ('is_superuser', models.BooleanField(db_column='superusuario', default=False, verbose_name='superusuario')),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_login', null=True, verbose_name='ultimo login')),
                ('date_joined', models.DateTimeField(db_column='data_cadastro', default=django.utils.timezone.now, verbose_name='data de cadastro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
